--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jojoe77777/FormAPI
branches:
- master
- pm4
projects:
  FormAPI:
    path: ""
  libFormAPI:
    path: ""
    type: library
    model: virion
...
